# Generated by Django 2.2.4 on 2019-09-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
