# Generated by Django 2.2.6 on 2019-10-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_admindetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsActiveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('statusString', models.CharField(max_length=30)),
            ],
        ),
    ]
