# Generated by Django 2.2.6 on 2019-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_modelsactivestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
