# Generated by Django 2.2.6 on 2019-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='username',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
